port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
bind-address: "*"
ipv6: false
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7894
  fallback-filter:
    geoip: false
    ipcidr:
      - 240.0.0.0/4

  nameserver:
    - https://42a755ec.d.adguard-dns.com/dns-query
    - tls://42a755ec.d.adguard-dns.com
    - tls://42a755ec.d.adguard-dns.com:853
    - quic://42a755ec.d.adguard-dns.com

  fallback:
    - tcp://94.140.14.59
    - tcp://94.140.14.49
    - 94.140.14.49
    - 94.140.14.59

tun:
  enable: true
  stack: system
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  dns-hijack:
    - tcp://108.137.44.39:53
experimental:
  interface-name: en0

proxies:
  - {
      name: sshocean-us,
      server: us1.v2rayserv.com,
      port: 443,
      type: vmess,
      uuid: b3eae015-2c74-4fc0-95bf-2bd8a9bb10b4,
      sni: us1.v2rayserv.com,
      alterId: 0,
      cipher: auto,
      tls: 1,
      skip-cert-verify: true,
      udp: true,
      network: ws,
      ws-opts: { path: /sshocean, headers: { Host: us1.v2rayserv.com } },
    }

  - {
      name: sshocean-uk,
      server: uk2.v2rayserv.com,
      port: 443,
      type: vmess,
      uuid: 391b66da-dc73-4708-af08-19366ea2d0ba,
      sni: uk2.v2rayserv.com,
      alterId: 0,
      cipher: auto,
      tls: 1,
      skip-cert-verify: true,
      udp: true,
      network: ws,
      ws-opts: { path: /sshocean, headers: { Host: uk2.v2rayserv.com } },
    }

proxy-groups:
  - name: sshocean
    type: url-test
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - sshocean-us
      - sshocean-uk

rules:
  - MATCH,sshocean
