port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
bind-address: "*"
ipv6: false
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7894
  fallback-filter:
    geoip: false
    ipcidr:
      - 240.0.0.0/4
  nameserver:
    - https://puredns.org/dns-query
    - tls://puredns.org:853
  fallback:
    - tcp://108.137.44.39
    - tcp://108.137.44.9
    - 108.137.44.39
    - 108.137.44.9
tun:
  enable: true
  stack: system
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  dns-hijack:
    - tcp://108.137.44.39:53
experimental:
  interface-name: en0

proxies:
  - {
    # https://sshstores.net/v2ray-region/vmess/london/lnvm7-2
      name: London02,
      server: ln.vmess2.xservs.xyz,
      port: 443,
      type: vmess,
      uuid: 77e2d891-857d-439f-afaa-e9ce3b0a0db1,
      sni: zoom.us,
      alterId: 0,
      cipher: auto,
      tls: 443,
      skip-cert-verify: true,
      udp: true,
      network: ws,
      ws-opts: { path: /vmess, headers: { Host: zoom.us } },
    }

    
  - {
    # https://sshstores.net/v2ray-region/vmess/japan/jpvm7-1
      name: Japan01,
      server: jp.vmess1.xservs.xyz,
      port: 443,
      type: vmess,
      uuid:  1d830892-83e5-4869-8b9b-64bb0001a2ec,
      sni: zoom.us,
      alterId: 0,
      cipher: auto,
      tls: 443,
      skip-cert-verify: true,
      udp: true,
      network: ws,
      ws-opts: { path: /vmess, headers: { Host: zoom.us } },
    }


  - {
    # https://sshstores.net/v2ray-region/vmess/netherland/nlvm7-1
      name: Neatherland01,
      server: nl.vmess1.xservs.xyz,
      port: 443,
      type: vmess,
      uuid:  8e33a578-7cf9-4840-8f16-34dbf9db156f,
      sni: zoom.us,
      alterId: 0,
      cipher: auto,
      tls: 443,
      skip-cert-verify: true,
      udp: true,
      network: ws,
      ws-opts: { path: /vmess, headers: { Host: zoom.us } },
    }

  - {
    # https://sshstores.net/v2ray-region/vmess/singapore/sgvm7-8
      name: Singapore08,
      server: sg.vmess8.xservs.xyz,
      port: 443,
      type: vmess,
      uuid:   8a7157a2-f274-4959-92c2-f8800cde0c75,
      sni: zoom.us,
      alterId: 0,
      cipher: auto,
      tls: 443,
      skip-cert-verify: true,
      udp: true,
      network: ws,
      ws-opts: { path: /vmess, headers: { Host: zoom.us } },
    }

  - {
    # https://sshstores.net/v2ray-region/vmess/usa/usvm7-3
      name: USA03,
      server: us.vmess3.xservs.xyz,
      port: 443,
      type: vmess,
      uuid:  ed25eec8-5f5c-4c79-ae88-45cd02898f57,
      sni: zoom.us,
      alterId: 0,
      cipher: auto,
      tls: 443,
      skip-cert-verify: true,
      udp: true,
      network: ws,
      ws-opts: { path: /vmess, headers: { Host: zoom.us } },
    }
  
proxy-groups:
  - name: personal-clash
    type: load-balance
    strategy: consistent-hashing
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - London02
      - Japan01
      - Neatherland01
      - Singapore08
      - USA03

rules:
  - MATCH,personal-clash
