port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
mode: global
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
bind-address: "*"
ipv6: false

dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7894
  fallback-filter:
    geoip: false
    ipcidr:
      - 240.0.0.0/4

  nameserver:
    - https://42a755ec.d.adguard-dns.com/dns-query
    - tls://42a755ec.d.adguard-dns.com
    - tls://42a755ec.d.adguard-dns.com:853
    - quic://42a755ec.d.adguard-dns.com

  fallback:
    - tcp://94.140.14.59
    - tcp://94.140.14.49
    - 94.140.14.49
    - 94.140.14.59

tun:
  enable: true
  stack: system
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  dns-hijack:
    - tcp://94.140.14.49:53
experimental:
  interface-name: en0

proxies:
  - {
      name: sshocean-uk,
      server: ukt1.sshocean.net,
      port: 443,
      udp: true,
      type: trojan,
      password: f712e634-a4f4-4fa3-8cc8-3a034820fabe,
      sni: zoom.us,
      skip-cert-verify: true,
    }

  - {
      name: sshocean-usa,
      server: ust2.sshocean.net,
      port: 443,
      udp: true,
      type: trojan,
      password: 0b3b9d3e-deb5-4e5b-b3bb-f63d7a101bea,
      sni: zoom.us,
      skip-cert-verify: true,
    }

  - {
      name: sshocean-sg,
      server: sgt3.sshocean.net,
      port: 443,
      udp: true,
      type: trojan,
      password: 2966331c-c25b-4d0f-8c2d-db21a24be8bd,
      sni: zoom.us,
      skip-cert-verify: true,
    }

  - {
      name: sshocean-sgt2,
      server: sgt3.sshocean.net,
      port: 443,
      udp: true,
      type: trojan,
      password: 144f85e9-8fa7-4128-b8b1-59b18ba317cc,
      sni,
      skip-cert-verify: true,
    }

proxy-groups:
  - name: sshkit-generator
    type: load-balance
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    strategy: consistent-hashing
    proxies:
      - sshocean-uk
      - sshocean-sgt2
      - sshocean-usa
      - sshocean-sg

rules:
  - MATCH,sshkit-generator
