port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
bind-address: "*"
ipv6: false
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7894
  fallback-filter:
    geoip: false
    ipcidr:
      - 240.0.0.0/4
  nameserver:
    - https://puredns.org/dns-query
    - tls://puredns.org:853
  fallback:
    - tcp://108.137.44.39
    - tcp://108.137.44.9
    - 108.137.44.39
    - 108.137.44.9
tun:
  enable: true
  stack: system
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  dns-hijack:
    - tcp://108.137.44.39:53
experimental:
  interface-name: en0

proxies:
  - {
    # https://sshstores.net/v2ray-region/vmess/london/lnvm7-2
      name: London02,
      server: ln.vmess2.xservs.xyz,
      port: 443,
      type: vmess,
      uuid: 4f1aa8aa-3b79-4aeb-9776-7f052dbf8028,
      sni: zoom.us,
      alterId: 0,
      cipher: auto,
      tls: 443,
      skip-cert-verify: true,
      udp: true,
      network: ws,
      ws-opts: { path: /vmess, headers: { Host: zoom.us } },
    }

    
  - {
    # https://sshstores.net/v2ray-region/vmess/japan/jpvm7-1
      name: Japan01,
      server: jp.vmess1.xservs.xyz,
      port: 443,
      type: vmess,
      uuid:  1d830892-83e5-4869-8b9b-64bb0001a2ec,
      sni: zoom.us,
      alterId: 0,
      cipher: auto,
      tls: 443,
      skip-cert-verify: true,
      udp: true,
      network: ws,
      ws-opts: { path: /vmess, headers: { Host: zoom.us } },
    }


  - {
    # https://sshstores.net/v2ray-region/vmess/sydney/auvm7-1
      name: Sydney01,
      server: au.vmess1.xservs.xyz,
      port: 443,
      type: vmess,
      uuid:  2d2cd344-b59e-44c3-920b-65a9403651df,
      sni: zoom.us,
      alterId: 0,
      cipher: auto,
      tls: 443,
      skip-cert-verify: true,
      udp: true,
      network: ws,
      ws-opts: { path: /vmess, headers: { Host: zoom.us } },
    }

  - {
    # https://sshstores.net/v2ray-region/vmess/singapore/sgvm7-8
      name: Singapore08,
      server: sg.vmess8.xservs.xyz,
      port: 443,
      type: vmess,
      uuid:   f14fa17a-af4e-4cae-918a-883acba85678,
      sni: zoom.us,
      alterId: 0,
      cipher: auto,
      tls: 443,
      skip-cert-verify: true,
      udp: true,
      network: ws,
      ws-opts: { path: /vmess, headers: { Host: zoom.us } },
    }

  - {
    # https://sshstores.net/v2ray-region/vmess/usa/usvm7-3
      name: Netherland01,
      server: nl.vmess1.xservs.xyz,
      port: 443,
      type: vmess,
      uuid:  1139735a-7f14-4841-a880-75a15fe2510b,
      sni: zoom.us,
      alterId: 0,
      cipher: auto,
      tls: 443,
      skip-cert-verify: true,
      udp: true,
      network: ws,
      ws-opts: { path: /vmess, headers: { Host: zoom.us } },
    }
  
proxy-groups:
  - name: personal-clash
    type: load-balance
    strategy: consistent-hashing
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - London02
      - Japan01
      - Sydney01
      - Singapore08
      - Netherland01

rules:
  - MATCH,personal-clash
